# Generated by Django 3.2.7 on 2021-10-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_bill_billdetails_companybank_employeebank_employeesalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
    ]
