# Generated by Django 3.2.7 on 2021-10-06 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211005_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.employee'),
        ),
    ]
