# Generated by Django 3.2.7 on 2021-10-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_bill_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebank',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CompanyBank',
        ),
        migrations.DeleteModel(
            name='EmployeeBank',
        ),
    ]
