# Generated by Django 3.2.7 on 2021-10-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211006_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billdetails',
            old_name='qty',
            new_name='Qty',
        ),
    ]
